image: node:11.6.0

pages:
  cache:
    paths:
      - sansbury-money/node_modules/

  script:
    - npm install -g yarn
    - (cd sansbury-money && yarn && yarn run build)
  artifacts:
    paths:
      - sansbury-money/build
  only:
    - master
