# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install -D --progress=false

unit test:
  image: node:12
  stage: test
  script:
    - npm run test
