version: '3'
services:
  web:
    build: ./frontend/app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app/src:/app/src
  api:
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data