version: "3"
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app/api
