version: "3"
services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
  api:
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app/api
      - ./delta:/app/delta
      - ./data:/app/data
